messages:
  takingItem: '[%d] [TAKE] %p подобрал предмет %n (%u) (x: %x, y: %y, z: %z)'
  takingItemFromPlayer: '[%d] [PLAYER] %p подобрал предмет %n (%u) который выбросил %p1, прошло %t сек. (x: %x, y: %y, z: %z)'
  droppingItem: '[%d] [DROP] %p выбросил предмет %n (%u) (x: %x, y: %y, z: %z)'
  killingItem: '[%d] [TAKE] %p подобрал предмет %n (%u) который выпал с игрока %p1 (x: %x, y: %y, z: %z)'
  chestTaking: '[%d] [CHEST] %p забрал предмет %n (%u), который положил игрок %p1 (x: %x, y: %y, z: %z)'
  npcDrop: '[%d] [NPC DROP] %p убил NPC и выбил %i'
  npcKilling: '[%d] [NPC KILL] %p убил %npc'